export declare enum Opcodes {
    NOP = 0,
    ADD = 1,
    ADDI = 2,
    SUB = 3,
    ADDF = 4,
    SUBF = 5,
    MULT = 6,
    MULTF = 7,
    OR = 8,
    AND = 9,
    XOR = 10,
    NOR = 11,
    SLLV = 12,
    SRLV = 13,
    SW = 14,
    SF = 15,
    LW = 16,
    LF = 17,
    BNE = 18,
    BEQ = 19,
    BGT = 20,
    OPERROR = 21,
}
export declare let OpcodesNames: string[];
